### ISSUE TITLE
Head Gesture and Eye Point of interest Component

### ISSUE THREAD

**Issue by Nazehyounsi** [intelligent-human-perception-laboratory/OpenSense#13]
Hello, 

I noticed that only the Visualizers of the HeadGesture and Eye Point of interest Components were available on the pipeline editor.
The HeadGesture Component and the POI component are missing, so we can't correctly build pipelines using these two important components.

Is there a way to simply add them ? Or you already planned to add them soon on this new version of OpenSense ? 

Thank you for your help and attention.

![image](https://user-images.githubusercontent.com/64654013/120663555-68571300-c48a-11eb-9727-1920b56b987e.png)

**Comment by KanaHayama** [comment]
Thank you for telling us this issue. It is because I forgot adding them as dependency. I've already updated the dependency list and uploaded a new binary release. 
I am closing this issue, if you have further questions, you can reopen it.
