### ISSUE TITLE
error when building OpenSense project

### ISSUE THREAD

**Issue by R-Raph** [intelligent-human-perception-laboratory/OpenSense#3]
I am trying to display the OpenSense application so i followed "How to build the codebase" but i have an issue when building the project. Do you have an idea ? thank you in advance. In the meantime ill try to solve my problem.
[build.txt](https://github.com/intelligent-human-perception-laboratory/OpenSense/files/6116809/build.txt)
![error](https://user-images.githubusercontent.com/70207357/110650439-d60cdf00-81ba-11eb-8324-7f444c0d8132.PNG)
![warning](https://user-images.githubusercontent.com/70207357/110650444-d6a57580-81ba-11eb-99cb-f9394f53e17b.PNG)

**Comment by KanaHayama** [comment]
The one in the `dev` branch is different, it requires additional Visual Studio workloads to be installed.
The document `How to build the codebase` only applies to the one in the `master` branch.
Are you able to build the version in the `master` branch?

**Comment by KanaHayama** [comment]
Projects shown in your error message are Windows Only components. They should be compiled using `x64` architecture, but not `Any CPU`. I already set those projects targeting `x64`, seems it does not work in your Visual Studio. You can change them manually on the top of Visual Studio.

**Comment by KanaHayama** [comment]
And also, please make sure you installed `.net framework 4.8`, and latest Windows SDK in your Visual Studio Installer.

**Comment by R-Raph** [comment]
I installed all the prerequisites indicated in the document how to build the codebase but indeed the box with the SDK 10.0.18362.0 was not checked. The master and dev branch now build successfully.
