### ISSUE TITLE
problem when adding an instance in pipeline editor

### ISSUE THREAD

**Issue by R-Raph** [intelligent-human-perception-laboratory/OpenSense#4]
When i'm trying to add an instance in the pipepile editor i get this screen immediatly after and when i click "continue" the next screenshot appear and then the application shut down.

![addproblem](https://user-images.githubusercontent.com/70207357/113002236-dffa8000-9171-11eb-851a-9689547d312d.PNG)

![addproblem1](https://user-images.githubusercontent.com/70207357/113004646-0d482d80-9174-11eb-82cc-9608312836a2.PNG)

in english the msg says : Reference assemblies should not be loaded for execution. They can only be loaded in the reflection loader context. Unable to load a reference assembly for execution.

Also in my project i want to use opensense on a video database (mp4 video) so i will not use a kinect. So is there a simple ways to solve this problem ? (and is it possible to use opensense with this kind of video ?)

**Comment by R-Raph** [comment]
I solve the first problem by installing https://www.microsoft.com/en-us/download/details.aspx?id=44561 even if the bug was not the same that in the Run section of tuto.

**Comment by kmstefanov** [comment]
Thanks for letting us know. I am closing the issue since the problem has been resolved.
